# SETTINGS FILE

# Device Type
MATRIX1 = "2236c5"
MATRIX2 = "f78b47"

# Internet Credentials
CIRCUITPY_WIFI_SSID = "o==[]:::::::::::::::::::::::::>"
CIRCUITPY_WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

# Matrix-specific API keys
ACCUWEATHER_API_KEY_TYPE1 = "YOUR_ACCUWEATHER_API_KEY_TYPE1"
ACCUWEATHER_API_KEY_TYPE2 = "YOUR_ACCUWEATHER_API_KEY_TYPE2"

# Keep the original as fallback
ACCUWEATHER_API_KEY = "YOUR_ACCUWEATHER_API_KEY_TYPE2"

# Accuweather Location Keys
ACCUWEATHER_LOCATION_KEY = "2626571"

# Fallback Timezone
TIMEZONE = "America/Chicago"

# Adafruit IO
ADAFRUIT_AIOS_USERNAME = "dcelayeta"
ADAFRUIT_AIO_KEY = "YOUR_ADAFRUIT_AIO_KEY"

# Timezone names from http://worldtimeapi.org/timezones
TIMEZONE = "America/Chicago"