# SETTINGS FILE

# Internet Credentials
CIRCUITPY_WIFI_SSID = "o==[]:::::::::::::::::::::::::>"
CIRCUITPY_WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

# Matrix-specific API keys
ACCUWEATHER_API_KEY_TYPE1 = "YOUR_ACCUWEATHER_API_KEY_TYPE2"
ACCUWEATHER_API_KEY_TYPE2 = "YOUR_ACCUWEATHER_API_KEY"

# Keep the original as fallback
ACCUWEATHER_API_KEY = "YOUR_ACCUWEATHER_API_KEY_TYPE2"

# Adafruit IO
ADAFRUIT_AIOS_USERNAME = "dcelayeta"
ADAFRUIT_AIO_KEY = "YOUR_ADAFRUIT_AIO_KEY"

# Timezone names from http://worldtimeapi.org/timezones
TIMEZONE = "America/Chicago"